import {EGGS,eggPreview,eggArt,incubationSeconds} from '../systems/EggSystem.js';
import {SHOP,EXPEDITIONS,RESOURCES,expeditionStatus} from '../systems/GameSystems.js';
import {UPGRADES,upgradeCost,upgradeLevel} from '../systems/UpgradeSystem.js';
import {SPECIES,rarityColors} from '../data.js';
import {qualityStars,patternName,profileSummary} from '../systems/GeneticsSystem.js';

export function shopScreen(state){return `<small>MERCADO FLUTUANTE</small><h2>Suprimentos</h2><p>Os Lúmens são compartilhados entre todos os tanques; cada habitat possui seu próprio preço de ovo.</p><div class="screen-grid">${SHOP.map(item=>{const i=item.kind==='egg'?{...item,...EGGS[state.biome],desc:`${eggPreview(state.biome)} · incubação ~${incubationSeconds(state,state.biome)}s`}:item;return `<button class="market-card" data-buy="${i.id}">${i.kind==='egg'?eggArt(state.biome):`<span>${i.icon}</span>`}<div><b>${i.name}</b><small>${i.desc}</small></div><em>✦ ${i.price}</em></button>`}).join('')}</div>`}

export function labScreen(state,creatures){
  const adults=creatures.filter(c=>['Adulto','Ancião'].includes(c.stage));
  return `<small>LABORATÓRIO GENÉTICO</small><h2>Linhagens e reprodução avançada</h2><p>Escolha dois adultos. O filhote cruza genes de tamanho, produtividade, velocidade, crescimento e vitalidade; pode herdar padrão de cor, melhorar qualidade e iniciar uma nova linhagem.</p><div class="resource-strip"><b>⬡ ${state.dna} DNA</b><b>Adultos: ${adults.length}</b></div><div class="lab-select genetics-lab">${adults.length?adults.map(c=>{const p=profileSummary(c);return `<label><input type="checkbox" name="parent" value="${c.uid}"><span style="--fish:${c.species.color}">◖</span><b>${c.species.name}</b><small class="quality-stars">${qualityStars(c.quality)}</small><small>G${p.generation} · ${patternName(c.genome?.pattern)} · Score ${p.score}</small></label>`}).join(''):'<div class="empty">Você ainda não possui duas criaturas adultas.</div>'}</div><div class="genetics-note">Filhotes de pais ★★★★–★★★★★ têm chance maior de nascer com qualidade superior. Mutações de cruzamento podem alterar genes e aparência.</div><button class="primary wide" id="breedBtn" ${adults.length<2||state.dna<4?'disabled':''}>Combinar genética · ⬡ 4</button>`}

export function expeditionScreen(state){const active=state.expedition,remaining=expeditionStatus(active);return `<small>EXPEDIÇÕES</small><h2>Explore além do aquário</h2><p>Envie uma equipe para buscar materiais usados nas melhorias permanentes. A missão continua com o jogo fechado.</p>${active?`<article class="active-expedition"><span>⌁</span><div><b>Expedição em andamento</b><small>${remaining?`Retorno em ${remaining}s`:'Equipe pronta para retornar'}</small></div><button id="claimExp" ${remaining?'disabled':''}>Coletar</button></article>`:''}<div class="screen-grid">${EXPEDITIONS.map(e=>`<button class="market-card" data-expedition="${e.id}" ${active||state.level<e.level?'disabled':''}><span>${e.icon}</span><div><b>${e.name}</b><small>${e.time}s · nível ${e.level}</small></div><em>${RESOURCES[e.reward].icon} ${e.amount}</em></button>`).join('')}</div>`}

export function sanctuaryScreen(state){return `<small>NÚCLEO DO SANTUÁRIO</small><h2>Aprimoramentos permanentes</h2><p>Use recursos raros para melhorar todos os habitats. Os níveis ficam salvos permanentemente.</p><div class="resource-strip"><b>◈ ${state.pearls} pérolas</b><b>◫ ${state.fossils} fósseis</b><b>◆ ${state.essence} essência</b><b>⬡ ${state.dna} DNA</b></div><div class="screen-grid upgrade-grid">${UPGRADES.map(u=>{const level=upgradeLevel(state,u.id),max=level>=u.max,cost=upgradeCost(state,u.id);return `<button class="market-card upgrade-card" data-upgrade="${u.id}" ${max?'disabled':''}><span>${u.icon}</span><div><b>${u.name}</b><small>${u.desc}</small><small class="upgrade-level">Nível ${level}/${u.max}</small></div><em>${max?'MÁXIMO':`${u.icon} ${cost}`}</em></button>`}).join('')}</div>`}

export function codexScreen(state){return `<small>ENCICLOPÉDIA ABISSAL</small><h2>${state.discovered.length} de ${SPECIES.length} espécies</h2><p>Cada espécie pode possuir inúmeras combinações genéticas, qualidades, padrões e linhagens.</p><div class="codex-grid">${SPECIES.map(s=>{const ok=state.discovered.includes(s.id);return `<div class="codex-entry ${ok?'':'unknown'}"><span style="color:${s.color}">${ok?'◖':'?'}</span><b>${ok?s.name:'Espécie desconhecida'}</b><small>${ok?`${s.type} · ${s.rarity}`:'Descubra em ovos e cruzamentos'}</small>${ok?`<i style="background:${rarityColors[s.rarity]}"></i>`:''}</div>`}).join('')}</div>`}
